name: vla
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytorch-gpu>=2.5
  - torchvision
  - torchaudio
  - numpy
  - scipy
  - pip
  - tensorboard
  - pillow
  - opencv
  - scikit-learn 
  - pip:
    - oyaml
    - dominate
    - ninja
    - ftfy
    - tqdm
    - regex
    - timm